using System.Runtime.InteropServices;

// Title/Description/Product/Copyright and every version attribute (AssemblyVersion, AssemblyFileVersion,
// AssemblyInformationalVersion) are generated by the SDK from SyncRADation.csproj, which reads the version
// from Bootstrap/PluginInfo.cs. Do not add version attributes here.
[assembly: ComVisible(false)]
[assembly: Guid("A1B2C3D4-E5F6-7890-ABCD-EF1234567890")]
