using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace SyncRADation.Tests
{
    /// <summary>
    /// Source-scan guard for identical-code-folding hazards (docs/RVA_FOLDING.md). No Unity, no game files:
    /// Data/FoldedRva.txt lists every method name that shares a native function with a patched method
    /// (generated by scripts/rva_fold_scan.py --write); this scans the mod sources for [HarmonyPatch] targets and fails when
    /// - a patch sits on an empty stub shared with thousands of methods ("removed"), or
    /// - a patch on a folded instance method does not start with Il2CppRealType.Is&lt;T&gt;(__instance).
    /// </summary>
    public class RvaFoldingTests
    {
        private sealed class Target
        {
            public string File, Class, Method;
            public int Line;
            public string Key => Class + "$$" + Method;
        }

        // The patched targets that sit on a folded RVA and therefore carry the guard. A new patch on a folded RVA
        // (or a guard dropped) changes this set: update docs/RVA_FOLDING.md + FoldedRva.txt together with it.
        private static readonly string[] ExpectedGuarded =
        {
            "Interaction$$reset", "Interaction$$setInRange", "ROT_MeatBlocker$$pickup", "ROT_Tarot$$flip",
        };

        private static readonly string[] ExpectedRemoved = { "MultiKeyLock$$Update" };

        private static readonly Lazy<string> Root = new Lazy<string>(() =>
        {
            string d = AppContext.BaseDirectory;
            while (d != null && !File.Exists(Path.Combine(d, "SyncRADation.csproj"))) d = Path.GetDirectoryName(d);
            Assert.NotNull(d);
            return d;
        });

        private static readonly Lazy<List<Target>> Targets = new Lazy<List<Target>>(ScanTargets);
        private static readonly Lazy<Dictionary<string, string>> Folded = new Lazy<Dictionary<string, string>>(LoadFolded);

        private static string ShortClass(string typeName)
        {
            string t = typeName.Replace("global::", "");
            int i = t.LastIndexOf('.');
            return i >= 0 ? t.Substring(i + 1) : t;
        }

        private static IEnumerable<string> SourceFiles()
        {
            foreach (string f in Directory.EnumerateFiles(Root.Value, "*.cs", SearchOption.AllDirectories))
            {
                string rel = f.Substring(Root.Value.Length).Replace('\\', '/');
                if (rel.StartsWith("/tests/") || rel.StartsWith("/obj/") || rel.StartsWith("/bin/") || rel.StartsWith("/dist/")
                    || rel.StartsWith("/.claude/") || rel.StartsWith("/.git/") || rel.StartsWith("/packages/")) continue;
                yield return f;
            }
        }

        private static List<Target> ScanTargets()
        {
            var list = new List<Target>();
            foreach (string path in SourceFiles())
            {
                string cur = null;
                string[] lines = File.ReadAllLines(path);
                for (int n = 0; n < lines.Length; n++)
                {
                    string line = lines[n];
                    foreach (Match m in Regex.Matches(line, @"HarmonyPatch\("))
                    {
                        int j = m.Index + m.Length, depth = 1;
                        while (j < line.Length && depth > 0)
                        {
                            if (line[j] == '(') depth++;
                            else if (line[j] == ')') depth--;
                            j++;
                        }
                        string a = line.Substring(m.Index + m.Length, j - 1 - (m.Index + m.Length));
                        Match mt = Regex.Match(a, @"^\s*typeof\(([\w.:]+)\)\s*$");
                        if (mt.Success) { cur = ShortClass(mt.Groups[1].Value); continue; }
                        Match mf = Regex.Match(a, @"^\s*typeof\(([\w.:]+)\)\s*,\s*(.*)$");
                        string cls = mf.Success ? ShortClass(mf.Groups[1].Value) : cur;
                        string rest = mf.Success ? mf.Groups[2].Value : a;
                        Match mm = Regex.Match(rest, "^\\s*(?:nameof\\(([\\w.:]+)\\)|\"(\\w+)\")");
                        Assert.True(mm.Success && cls != null, path + ":" + (n + 1) + " unparsed [HarmonyPatch(" + a + ")]");
                        string name = (mm.Groups[1].Success ? mm.Groups[1].Value : mm.Groups[2].Value);
                        name = name.Substring(name.LastIndexOf('.') + 1);
                        list.Add(new Target { File = path, Line = n + 1, Class = cls, Method = name });
                    }
                }
            }
            return list;
        }

        private static Dictionary<string, string> LoadFolded()
        {
            var d = new Dictionary<string, string>();
            string path = Path.Combine(Root.Value, "tests", "SyncRADation.Tests", "Data", "FoldedRva.txt");
            foreach (string raw in File.ReadAllLines(path))
            {
                string ln = raw.Trim();
                if (ln.Length == 0 || ln[0] == '#') continue;
                string[] p = ln.Split('\t');
                Assert.Equal(3, p.Length);
                d[p[1]] = p[0];
            }
            return d;
        }

        /// <summary>Text of the first brace block after the attribute line: the patch class (class-level attribute) or the patch method.</summary>
        private static string BlockAfter(Target t)
        {
            string[] lines = File.ReadAllLines(t.File);
            var sb = new System.Text.StringBuilder();
            for (int i = t.Line - 1; i < lines.Length; i++) sb.Append(lines[i]).Append('\n');
            string s = sb.ToString();
            int open = s.IndexOf('{');
            Assert.True(open > 0);
            int depth = 0, k = open;
            for (; k < s.Length; k++)
            {
                if (s[k] == '{') depth++;
                else if (s[k] == '}' && --depth == 0) break;
            }
            return s.Substring(open, k - open + 1);
        }

        private static IEnumerable<string> HookBodies(string block)
        {
            foreach (Match m in Regex.Matches(block, @"public static \w+ (?:Prefix|Postfix)\w*\([^)]*\)\s*(=>|\{)"))
                yield return block.Substring(m.Index + m.Length - (m.Groups[1].Value == "{" ? 1 : 2));
        }

        [Fact]
        public void Scanner_finds_the_patch_set()
        {
            Assert.True(Targets.Value.Count >= 190, "found only " + Targets.Value.Count + " [HarmonyPatch] targets: scanner out of date?");
            Assert.Contains(Targets.Value, t => t.Key == "Interaction$$reset");
        }

        [Fact]
        public void Removed_stub_targets_are_not_patched()
        {
            foreach (string key in ExpectedRemoved) Assert.Equal("removed", Folded.Value[key]);
            var bad = Targets.Value.Where(t => Folded.Value.TryGetValue(t.Key, out string a) && a == "removed")
                .Select(t => t.Key + " (" + Path.GetFileName(t.File) + ":" + t.Line + ")").ToList();
            Assert.True(bad.Count == 0, "patch on an empty stub shared with thousands of methods: " + string.Join(", ", bad)
                + " — remove it (docs/RVA_FOLDING.md)");
        }

        [Fact]
        public void Every_patch_on_a_folded_instance_method_is_guarded_with_Il2CppRealType_first()
        {
            var problems = new List<string>();
            foreach (Target t in Targets.Value)
            {
                if (!Folded.Value.TryGetValue(t.Key, out string action) || action != "guard") continue;
                string block = BlockAfter(t);
                var bodies = HookBodies(block).ToList();
                if (bodies.Count == 0) { problems.Add(t.Key + ": no Prefix/Postfix found"); continue; }
                string want = "if (!Il2CppRealType.Is<" + t.Class + ">(__instance))";
                foreach (string body in bodies)
                {
                    string first = body.Substring(body.IndexOf('{') + 1);
                    // skip blank lines and // comments, then the first statement must be the guard
                    first = Regex.Replace(first, @"^(\s|//[^\n]*\n)*", "");
                    if (!first.StartsWith(want, StringComparison.Ordinal))
                        problems.Add(t.Key + " (" + Path.GetFileName(t.File) + ":" + t.Line + "): first statement must be `" + want + " return ...;`");
                }
            }
            Assert.True(problems.Count == 0, string.Join("\n", problems));
        }

        [Fact]
        public void The_guarded_patch_list_is_pinned()
        {
            var actual = Targets.Value.Where(t => Folded.Value.TryGetValue(t.Key, out string a) && a == "guard")
                .Select(t => t.Key).Distinct().OrderBy(x => x, StringComparer.Ordinal).ToArray();
            Assert.Equal(ExpectedGuarded.OrderBy(x => x, StringComparer.Ordinal).ToArray(), actual);
        }

        [Fact]
        public void Doc_table_names_every_guarded_and_removed_target()
        {
            string doc = File.ReadAllText(Path.Combine(Root.Value, "docs", "RVA_FOLDING.md"));
            foreach (string key in ExpectedGuarded.Concat(ExpectedRemoved))
                Assert.Contains("`" + key.Replace("$$", ".") + "`", doc);
        }
    }
}
