#!/usr/bin/env python3
"""Find Harmony patch targets whose native function is shared with other methods (identical code folding).

IL2CPP builds fold byte-identical methods into ONE native function; script.json then lists several names at one RVA.
A Harmony detour on such a method fires for every one of them, with `this` of a foreign class. See docs/RVA_FOLDING.md.

Usage:
  scripts/rva_fold_scan.py              # print the table of folded targets
  scripts/rva_fold_scan.py --write      # also regenerate the table section of docs/RVA_FOLDING.md and
                                        # tests/SyncRADation.Tests/Data/FoldedRva.txt (the list RvaFoldingTests pins)
  scripts/rva_fold_scan.py --check      # exit 1 if a patched target is folded but missing from FoldedRva.txt

Needs the Il2CppDumper output (script.json). Override the location with --script-json or SIGNALIS_SCRIPT_JSON.
"""
import argparse
import collections
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DEFAULT_JSON = os.path.expanduser("~/Archive/Windows-Desktop/Dev/SIGNALIS DECOMPILED/01_Il2CppDumper/script.json")
DATA_FILE = os.path.join(ROOT, "tests", "SyncRADation.Tests", "Data", "FoldedRva.txt")
DOC_FILE = os.path.join(ROOT, "docs", "RVA_FOLDING.md")
SKIP_DIRS = ("/obj", "/bin", "/.claude", "/tests", "/dist", "/.git", "/packages")
# Targets that were patched once and must stay unpatched; listed so the table and FoldedRva.txt keep documenting them.
KNOWN_REMOVED = [("MultiKeyLock", "Update", None)]
STUB_MIN = 50  # a group this large is an empty stub / trivial getter shared with thousands of methods
TABLE_BEGIN = "<!-- rva-table:begin (generated by scripts/rva_fold_scan.py --write) -->"
TABLE_END = "<!-- rva-table:end -->"

PARAM_PREFIX = {
    "int": "int32_t", "string": "System_String_o*", "float": "float", "bool": "bool", "AnItem": "AnItem_o*",
    "Vector3": "UnityEngine_Vector3_o", "Il2CppSystem.Guid": "System_Guid_o", "GameObject": "UnityEngine_GameObject_o*",
    "DialoguerCallback": "DialoguerCallback_o*", "Items.itemlist": "int32_t",
}


def patch_targets():
    """(file, line, class, method, arg types | None) for every [HarmonyPatch(...)] in the mod sources."""
    out = []
    for dp, _, files in os.walk(ROOT):
        # Relative to ROOT: a checkout inside .claude/worktrees/ must not skip itself.
        rel = "/" + os.path.relpath(dp, ROOT).replace(os.sep, "/")
        if any(s in rel for s in SKIP_DIRS):
            continue
        for f in files:
            if not f.endswith(".cs"):
                continue
            path = os.path.join(dp, f)
            cur = None
            with open(path, encoding="utf-8", errors="replace") as fh:
                for n, line in enumerate(fh, 1):
                    for m in re.finditer(r"HarmonyPatch\(", line):
                        j, depth = m.end(), 1
                        while j < len(line) and depth:
                            depth += {"(": 1, ")": -1}.get(line[j], 0)
                            j += 1
                        a = line[m.end():j - 1]
                        mt = re.match(r"^\s*typeof\(([\w.:]+)\)\s*$", a)
                        if mt:
                            cur = mt.group(1).replace("global::", "")
                            continue
                        mf = re.match(r"^\s*typeof\(([\w.:]+)\)\s*,\s*(.*)$", a)
                        cls, rest = (mf.group(1).replace("global::", ""), mf.group(2)) if mf else (cur, a)
                        mm = re.match(r'^\s*(?:nameof\(([\w.:]+)\)|"(\w+)")\s*(?:,\s*(.*))?$', rest)
                        if not mm:
                            print("UNPARSED", path, n, line.strip(), file=sys.stderr)
                            continue
                        name = (mm.group(1) or mm.group(2)).split(".")[-1]
                        arg = mm.group(3)
                        args = None
                        if arg:
                            args = [] if "Type[0]" in arg else re.findall(r"typeof\(([\w.:]+)\)", arg)
                        out.append((os.path.relpath(path, ROOT), n, cls, name, args))
    return out


def param_types(sig):
    ps = [p.strip() for p in re.search(r"\((.*)\)", sig).group(1).split(",") if p.strip()]
    return [p for p in ps if not p.startswith("const MethodInfo") and "__this" not in p]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--script-json", default=os.environ.get("SIGNALIS_SCRIPT_JSON", DEFAULT_JSON))
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    opt = ap.parse_args()

    methods = json.load(open(opt.script_json))["ScriptMethod"]
    by_name, by_addr, static_name = collections.defaultdict(list), collections.defaultdict(set), {}
    for e in methods:
        by_name[e["Name"]].append(e)
        by_addr[e["Address"]].add(e["Name"])
        static_name[e["Name"]] = static_name.get(e["Name"], True) and "__this" not in e["Signature"]

    rows, unresolved = [], []
    targets = patch_targets() + [("(patch removed)", 0, c, n, a) for c, n, a in KNOWN_REMOVED]
    for f, line, cls, name, args in targets:
        short = cls.split(".")[-1]
        cands = []
        for nm in (name, "get_" + name, "set_" + name):
            for k, v in by_name.items():
                if k.endswith("$$" + nm):
                    c = k.split("$$")[0]
                    if c == cls or c.split(".")[-1] == short or c.endswith("." + short):
                        cands += v
            if cands:
                break
        if args is not None:
            def ok(e):
                ps = param_types(e["Signature"])
                return len(ps) == len(args) and all(not PARAM_PREFIX.get(a) or p.startswith(PARAM_PREFIX[a]) for p, a in zip(ps, args))
            cands = [e for e in cands if ok(e)]
        if not cands:
            unresolved.append((f, line, cls, name))
            continue
        own = {e["Name"] for e in cands}
        for addr in sorted({e["Address"] for e in cands}):
            others = sorted(n for n in by_addr[addr] if n not in own)
            rows.append({"cls": cls, "name": name, "args": args, "addr": addr, "others": others, "own": sorted(own),
                         "where": "%s:%d" % (f, line), "static": all(static_name[o] for o in own)})

    checked = len(rows) + len(unresolved)
    folded = [r for r in rows if r["others"]]
    print("%d patch targets, %d unresolved, %d folded" % (checked, len(unresolved), len(folded)))
    for u in unresolved:
        print("  UNRESOLVED", u)
    for r in folded:
        print("  %s.%s%s @0x%X shares with %d: %s  [%s]" % (
            r["cls"], r["name"], "(" + ",".join(r["args"]) + ")" if r["args"] else "", r["addr"], len(r["others"]),
            ", ".join(r["others"][:5]), r["where"]))

    for r in folded:
        r["action"] = action_for(r)

    if opt.check:
        known = load_data()
        bad = [r for r in folded if ("%s$$%s" % (r["cls"].split(".")[-1], r["name"])) not in known]
        for r in bad:
            print("NOT LISTED in FoldedRva.txt: %s.%s" % (r["cls"], r["name"]))
        sys.exit(1 if bad else 0)

    if opt.write:
        write_data(folded, by_addr, static_name)
        write_doc(folded, checked)
        print("wrote", os.path.relpath(DATA_FILE, ROOT), "and", os.path.relpath(DOC_FILE, ROOT))


def action_for(r):
    if len(r["others"]) + 1 >= STUB_MIN:
        return "removed"  # no patch allowed: it would run for every method sharing the stub
    return "static" if r["static"] else "guard"


THIRD_PARTY = r"^(System|Mono|Microsoft|UnityEngine|Unity|I18N|Rewired|Sirenix|Pathfinding|ExternalTool|TMPro|Steamworks|Newtonsoft|Cinemachine|DG|Xbox|Microsoft)\b"


def keep_member(name):
    """Stub members worth pinning: game classes. Third-party / compiler-generated names are noise (nobody patches them)."""
    cls = name.split("$$")[0]
    if re.match(THIRD_PARTY, cls) or ".<" in cls or "System.IDisposable" in name:
        return False
    return not re.match(r"^[A-Za-z]{20,}(\$|\.|<|$)", cls)  # obfuscated class names


def short_name(n):
    c, m = n.split("$$", 1)
    return "%s$$%s" % (c.split(".")[-1], m) if "." in c and "<" not in c else n


def load_data():
    known = {}
    if os.path.exists(DATA_FILE):
        for ln in open(DATA_FILE):
            ln = ln.strip()
            if ln and not ln.startswith("#"):
                act, nm, _ = ln.split("\t")
                known[nm] = act
    return known


def write_data(folded, by_addr, static_name):
    lines = ["# Generated by scripts/rva_fold_scan.py --write. Consumed by RvaFoldingTests.",
             "# action<TAB>Class$$Method<TAB>RVA. Every name at a folded RVA shared with a patched method.",
             "#   removed: empty stub shared with thousands of methods, must NOT be patched",
             "#   guard  : instance method, a patch on it must start with Il2CppRealType.Is<T>(__instance)",
             "#   static : no `this` (same-signature static wrappers), no guard possible or needed"]
    seen = set()
    for r in sorted(folded, key=lambda x: (x["addr"], x["cls"], x["name"])):
        names = set(r["own"]) | set(r["others"])
        for n in sorted(names):
            if r["action"] == "removed" and n not in r["own"] and not keep_member(n):
                continue
            act = r["action"]
            if act != "removed":
                act = "static" if static_name[n] else "guard"
            sn = short_name(n) if "$$" in n and "<" not in n.split("$$")[0] else n
            key = (act, sn)
            if key in seen:
                continue
            seen.add(key)
            lines.append("%s\t%s\t0x%X" % (act, sn, r["addr"]))
    os.makedirs(os.path.dirname(DATA_FILE), exist_ok=True)
    with open(DATA_FILE, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_doc(folded, checked):
    rows = ["| Target | RVA | Shared with | Action |", "|---|---|---|---|"]
    for r in sorted(folded, key=lambda x: (x["addr"], x["cls"], x["name"])):
        tgt = "`%s.%s%s`" % (r["cls"], r["name"], "(%s)" % ",".join(r["args"]) if r["args"] else "")
        others = r["others"]
        shown = ", ".join("`%s`" % n for n in others[:4])
        if len(others) > 4:
            shown += ", and %d more" % (len(others) - 4)
        act = {"removed": "**Patch removed**; purpose moved to the 0.5 s poll",
               "guard": "Guarded: `Il2CppRealType.Is<%s>(__instance)` first" % r["cls"].split(".")[-1],
               "static": "None: static, same parameters, nested guard in `DialoguerGate`"}[r["action"]]
        rows.append("| %s | `0x%X` | %s | %s |" % (tgt, r["addr"], shown, act))
    block = "%s\n\n%d patch targets checked, %d folded.\n\n%s\n\n%s" % (TABLE_BEGIN, checked, len(folded), "\n".join(rows), TABLE_END)
    text = open(DOC_FILE).read() if os.path.exists(DOC_FILE) else ""
    if TABLE_BEGIN in text:
        pre = text[:text.index(TABLE_BEGIN)]
        post = text[text.index(TABLE_END) + len(TABLE_END):]
        text = pre + block + post
    else:
        text += "\n" + block + "\n"
    open(DOC_FILE, "w").write(text)


if __name__ == "__main__":
    main()
